name: mishos
root: ~/projects/mishos

windows:
  - api:
      root: ~/projects/mishos/api
      panes:
        - yarn start:dev
  - web:
      root: ~/projects/mishos/web
      panes:
        - yarn dev
  - editor:
      root: ~/projects/mishos/web
      panes:
        - nvim .
