services:
  mishos:
    image: bljohnsondev/mishos:latest
    container_name: mishos
    ports:
      - 8080:80
    environment:
      - TZ=America/Chicago
      - DB_TYPE=sqlite
      - DB_URL=/db/mishos.db
      - SECRET=YOUR_SECRET_KEY_HERE
      - WATCHLIST_RECENT_LIMIT=30
      - TOKEN_DURATION=90
      # - CRON_PROVIDER_UPDATE=21 8 * * *
      # - RUN_MIGRATION=1
    volumes:
      - /home/brent/temp/mishos:/db
    restart: unless-stopped
